### ISSUE TITLE
Cherry pick uplink auth to this release.

### ISSUE THREAD

**Issue by lijunle** [Zevran/sinopia#11]
Pull request from @lea-anthony : https://github.com/rlidwka/sinopia/pull/269

**Comment by gaelreyrol** [comment]
Hello @lijunle 

Sorry for the delay.

Thanks I've merged the commit, indeed it's useful !

**Comment by leaanthony** [comment]
Sorry for the lack of response! Glad this has been of use to people.

Regards.
